name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.2.0]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Deploy to production
        uses: awibox/deploy-to-github-pages-action@master
        env:
          AUTHOR: menlib
          BUILD_PATH: public
          GITHUB_PAGE_NAME: menlib.github.io
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: menlib
          EMAIL: menlisha00@gmail.com